= Build API Docs for the RHQ Project 
:hp-tags: Maven, RHQ, API Docs

Granted, this blog post will only likely interest the following audience:

* Red Hat associates.
* Folks using the upstream RHQ project. 
* Folks interested in techniques for generating API docs using Maven.

== The Terse Process

The general process for building this project's API docs is:

. `$ yum install maven`
. `$ git clone https://github.com/rhq-project/rhq.git jon`
. `$ cd jon`
. `$ cd modules/enterprise/server/jar`
. `$ mvn -Ddocgen install  (or compile)`

But as I found out, there is a little more to it than that.

=== First Attempt: No Success

I ran the steps in the process, and sat back with a cuppa tea...

Note the build time...

[source,bash]
----
Downloaded: http://repo.maven.apache.org/maven2/org/mockito/mockito-all/1.9.0/mockito-all-1.9.0.jar (1461 KB at 76.0 KB/sec)
Downloaded: http://repo.maven.apache.org/maven2/org/testng/testng/6.5.2/testng-6.5.2.jar (701 KB at 36.4 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15:13 min
[INFO] Finished at: 2015-02-16T10:00:51+10:00
[INFO] Final Memory: 19M/242M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project rhq-enterprise-server: Could not resolve dependencies for project org.rhq:rhq-enterprise-server:ejb:4.14.0-SNAPSHOT: The following artifacts could not be resolved: org.rhq:rhq-enterprise-comm:jar:4.14.0-SNAPSHOT, org.rhq:rhq-enterprise-server-xml-schemas:jar:4.14.0-SNAPSHOT, org.rhq:rhq-core-domain:jar:4.14.0-SNAPSHOT, org.rhq:rhq-cassandra-schema:jar:4.14.0-SNAPSHOT, org.rhq:rhq-core-plugin-api:jar:4.14.0-SNAPSHOT, org.rhq:rhq-core-client-api:jar:4.14.0-SNAPSHOT, org.rhq:rhq-core-dbutils:jar:4.14.0-SNAPSHOT, org.rhq:safe-invoker:jar:4.14.0-SNAPSHOT, org.rhq:rhq-common-drift:jar:4.14.0-SNAPSHOT, org.rhq:rhq-server-metrics:jar:4.14.0-SNAPSHOT, org.rhq:rhq-cassandra-util:jar:4.14.0-SNAPSHOT, org.rhq:rhq-jboss-as-dmr-client:jar:4.14.0-SNAPSHOT, org.rhq:test-utils:jar:4.14.0-SNAPSHOT, org.rhq.helpers:rest-docs-generator:jar:4.14.0-SNAPSHOT, org.rhq:rhq-core-domain:jar:tests:4.14.0-SNAPSHOT: Could not find artifact org.rhq:rhq-enterprise-comm:jar:4.14.0-SNAPSHOT in sonatype-snapshots (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
----

I can't really complain about this though: the first time you build a Maven project, you can expect it to take a long time as it downloads the required dependencies.

The issue now is that I need to build the required dependencies myself before the DocGen tool can work.

=== Second Attempt: Build Deps

Luckily the folks in the RHQ project have made dependency building as simple as possible. 

In the root of the project there is this script: 

`$ ./build-deps.sh`

Run this script, and it orchestrates the dependency build process for the project. This type of automation is great for folks wanting to easily build the project. Great work RHQ team! 

The script and the resulting process completed successfully, and I thought I was ready to run DocGen.

Not. So. Fast.

=== Third Attempt: Run DogGen at Project Root

[source,bash]
----
[INFO] ------------------------------------------------------------------------
[INFO] Building RHQ Enterprise Server JAR 4.14.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.rhq:rhq-enterprise-comm:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-enterprise-server-xml-schemas:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-core-domain:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-cassandra-schema:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-core-plugin-api:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-core-client-api:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-core-dbutils:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:safe-invoker:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-common-drift:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-server-metrics:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-cassandra-util:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-jboss-as-dmr-client:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:test-utils:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq.helpers:rest-docs-generator:jar:4.14.0-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.rhq:rhq-core-domain:jar:tests:4.14.0-SNAPSHOT is missing, no dependency information available
----

Still no bueno with DocGen.

At this point, I hit a dead end. 

I thought perhaps the following step was wrong: 

	4) `$ cd modules/enterprise/server/jar`

Perhaps I needed to execute `$ mvn -Ddocgen install` at the project root?

I executed the command at project root and things certainly looked promising. Maven began downloading a whole stack of dependencies that related to the platform. But as a Maven n00b, I learned after 11 minutes that this was a false sense of security. By executing the DocGen command at the project root, maven took the configuration in the root pom.xml file and began compiling the *entire project*. 

Should have trusted the instructions on that one. But the positive out of this was I got a refresher about how Maven works. Lets chalk this up to experience.

[quote,a Maven Warlock Lvl10]
____
Build only what you need, at the level you need.
____

Good advice for sure.

== The End Result

The Bad News::
Well, I have hit a dead end. I'm not able to generate the API Docs at the moment.
    
The Good News::
I work with the RHQ team at Red Hat, as part of my job as the Docs Writer for the product docs. To ensure other users don't have the same issues with building the RHQ project as I did, I created https://bugzilla.redhat.com/show_bug.cgi?id=1192869 to start discussing ways the missing dependencies can be packaged in the Maven build.

To Be Continued...