= Caffeingineering 101

:hp-tags: Coffee, Nerd, 

I've been wondering how to break the ice with this new blog.

Now, it may be the fact that I've only had 5 hours of sleep because I staggered into my home office at 3:30 am this morning to get a jump on the day, but as I poured my fourth cup of coffee, I realised that a perfectly serviceable post topic was right under my nose; coffee.

Or more specifically; the way I consume it.

We hear people go on all the time about how addicted to coffee they are. They have their coffee themed tee-shirts and their tongue-in-cheek coffee mug. Frankly they annoy the piss out of me.

Because I am a coffee addict. And I know what the term 'addict' actually means (hint; it doesn't mean "I enjoy a tipple when the opportunity arises").

I'm an addict in the way a smack addict is. I'd lick spilt coffee off the kitchen floor if it was my only option for a caffeine hit.

So when I say this post is for other coffee addicts, I want you to be **very** clear who I'm talking to. __Soy mocha latte__ sipping poseurs need not read any further.

== Mothered by necessity

I usually drink my coffee strong and black.

But sometimes (today for example) the usual just isn't going to cut it. That's when I like to roll out one of my two secret-recipe coffee treats.

And today I've decided to share those recipes with the world.

Once again, be warned. Unless you've ever seriously...and I mean **seriously**...considered spooning instant coffee directly into your face, stop reading now.

== Roll on!

If I'm having a hard time keeping up with the day, I go for what I think of as a 'rolling' cup of coffee.

Basically, this style of coffee gets stronger as the day goes on, keeping you moving during those times when the effort to continue breathing in and out seems to be less and less worth it.

What you need do is:

. Make yourself a cup of coffee in your preferred style (black, no sugar, obviously).
. Drink about three quarters of the cup.
. Take the remaining dregs back to the kitchen and, without emptying your cup first, make another coffee.
. Don't rinse, just repeat.

The more coffees you have in a day, the stronger the dregs in your cup will be and the stronger they, in turn, will make the next cup. 

== The Cokeacino

This one is strictly for the hard core. Proceed at your own risk.

If you need a serious boost in a serious hurry, nothing beats a Cokeacino. 

To enjoy this marvel of caffeingineering (and the heart palpitations that invariably follow it):

. Make a **half** cup of your coffee of choice. Don't skimp on the ingredients, mind you, just stop adding water when the cup is half full. Your coffee is now twice as strong by volume.
. Head to the nearest vending machine and grab a Coca Cola (TM).
. Top off your cup with tasty cola. **Do this carefully as it will froth like a sonofabitch!**
. Slam down what's left in the can like you're skulling beer in an __Animal House__ remake.
. Drink your coffee. Don't worry; you'll get used to the sensation of carbonated coffee remarkably quickly.
. Try not to have a fucking heart attack as you surf the caffeine tsunami.


=== Don't sue me

Seriously, just don't. I can't stress this enough. If you try one of these drinks and your heart explodes, don't fucking take it out on me. 

Maybe next time you should go for a nice, hot cup of concrete.
